### ISSUE TITLE
Only fixed params of logistic model are used for calling the core method after fitting

### ISSUE THREAD

**Issue by yunchienchang** [kusterlab/curve_curator#25]
Here the fixed parameters are taken although a model has been fitted and is then raising an error...
https://github.com/kusterlab/curve_curator/blob/b87b2126f27b5223ad395cc3720b11af5f04f139/curve_curator/models.py#L864

Example:
```python
# data
line_x = np.linspace(-10.3, -4.3, 1000)
x = np.log10([0.1, 1.0, 10.0, 30.0, 100.0, 300.0, 1000.0, 3000.0, 10000.0, 30000.0]) - 9
y = pd.Series([1, 1, 4, 6, 7, 16, 55, 105, 147, 160])


# Define the logistic Model
logistic_model = LogisticModel()

# Fit the unrestricted model with ordinary least squares (ols)
logistic_model.find_best_guess_ols(x, y)
logistic_model.fit_ols(x,y)
logistic_model(line_x)
```

Error message:
`TypeError: LogisticModel.core() missing 4 required positional arguments: 'pec50', 'slope', 'front', and 'back'`

**Comment by yunchienchang** [comment]
https://github.com/kusterlab/curve_curator/blob/b87b2126f27b5223ad395cc3720b11af5f04f139/curve_curator/models.py#L302

**Comment by FloBay** [comment]
Quick solution is to actively pass the fitted params after fitting. 

```python
logistic_model(line_x, **logistic_model.get_all_parameters())
```

But I agree. It would be a nicer API call.

**Comment by FloBay** [comment]
Idea: follow scikit-learn logic of fit and predict methods. Easy solution is a high level predict function that works after all parameters are available

```python
# Define the logistic Model
logistic_model = LogisticModel()

# Fit the unrestricted model with ordinary least squares (ols)
logistic_model.find_best_guess_ols(x, y)
logistic_model.fit_ols(x, y)
logistic_model.predict(line_x)
```
