### ISSUE TITLE
PD Example question

### ISSUE THREAD

**Issue by PSobrevalsAlcaraz** [kusterlab/curve_curator#26]
Good morning,

First of all congratulations on this useful tool :)

I have data output from PD with triplicates. While looking into your TOML examples, I noticed there's an example for triplicates, but unfortunately, I couldn't find any example specific to PD. Could you give an example for PD output data? I've been trying to implement it but haven't succeeded so far. Any help would be greatly appreciated!

Thank you,
Paula

PD: For the control setting on TOML, should we add all the sample names of the control curve or only the 0 value?

**Comment by FloBay** [comment]
Hey Paula,

Thanks for testing CurveCurator.
It all depends a bit on the specific setup you have, and PD is especially painful in this regard.

My experience is that the easiest / fastest way is to send me a small example of the PD file (column names + 5 rows - not all) you tried to put in and your current toml. Then, I have a quick look and can come back to you...
my email: f.bayer@tum.de

To your question: "For the control setting on TOML, should we add all the sample names of the control curve or only the 0 value?"
Not sure if I fully get it. What is your control curve? Or do you mean the controls of the curves to which the ratio is calculated?


Best
Flo

**Comment by PSobrevalsAlcaraz** [comment]
Hi Flo,

Thank you so much for your short reply!
I'm sorry to hear PD is complicated in this regard. I will see if we can search it through another engine next time...
I send you an email with the small example.

Thank you so much!
Paula

**Comment by FloBay** [comment]
Solved. 

No need to change the search engine.
