### ISSUE TITLE
Make dashboard (i.e. Gene, Name) search case insensitive

### ISSUE THREAD

**Issue by StephanEckert** [kusterlab/curve_curator#30]
Dear Florian Bayer,

I would be highly grateful if you could make the search function in the dashboard case INsensitive. My pinky already hurts from pressing down the shift key. 

Thanks a lot!

Stephan Eckert

**Comment by FloBay** [comment]
I added a checker box that can enable and disable case-sensitive text searches.

The new feature looks like this :
![image](https://github.com/user-attachments/assets/7ef225fd-b6b0-4b76-80a3-ebe3ffb6f815)

Some regex queries may only be available in the case-sensitive mode
